// Finds failed Windows login attempts from a specific attacker IP
// Uses Sentinel Watchlist to map attacker IPs to locations

let GeoIPDB_FULL = _GetWatchlist("geoip");
let WindowsEvents = SecurityEvent
    | where IpAddress == // <attacker IP address('in quotes')>
    | where EventID == 4625
    | order by TimeGenerated desc
    | evaluate ipv4_lookup(GeoIPDB_FULL, IpAddress, network);
WindowsEvents
